# Generated by Django 5.1.15 on 2026-07-02 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('trip', 'trip'), ('home', 'home'), ('couple', 'couple'), ('other', 'other')], default='other', max_length=10)),
                ('cover_url', models.TextField(blank=True, null=True)),
                ('base_currency', models.CharField(default='INR', max_length=3)),
                ('default_split_config', models.JSONField(blank=True, null=True)),
                ('rotation_enabled', models.BooleanField(default=False)),
                ('rotation_mode', models.CharField(choices=[('balanced', 'balanced'), ('round_robin', 'round_robin')], default='balanced', max_length=12)),
                ('rotation_rr_order', models.JSONField(default=list)),
                ('rotation_rr_pos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('status', models.IntegerField()),
                ('body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idempotency_records',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('name', models.TextField()),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('upi_vpa', models.TextField(blank=True, null=True)),
                ('default_currency', models.CharField(default='INR', max_length=3)),
                ('locale', models.TextField(default='en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount_paise', models.BigIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('expense_date', models.DateField()),
                ('source', models.CharField(choices=[('manual', 'manual'), ('nl', 'nl'), ('import', 'import')], default='manual', max_length=6)),
                ('is_rotation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.group')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to='core.user')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.BigIntegerField()),
                ('method', models.CharField(choices=[('upi', 'upi'), ('manual', 'manual')], max_length=6)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('disputed', 'disputed'), ('cancelled', 'cancelled')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='core.group')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_paid', to='core.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to='core.user')),
            ],
            options={
                'db_table': 'settlements',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups_created', to='core.user'),
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('target', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='core.user')),
            ],
            options={
                'db_table': 'activity_events',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'owner'), ('member', 'member')], default='member', max_length=6)),
                ('in_rotation', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.user')),
            ],
            options={
                'db_table': 'group_members',
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='uq_group_member')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.user')),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.user')),
            ],
            options={
                'db_table': 'friendships',
                'constraints': [models.UniqueConstraint(fields=('user_low', 'user_high'), name='uq_friendship'), models.CheckConstraint(condition=models.Q(('user_low__lt', models.F('user_high'))), name='ck_friend_order')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_paise', models.BigIntegerField(default=0)),
                ('owed_paise', models.BigIntegerField(default=0)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_shares', to='core.user')),
            ],
            options={
                'db_table': 'expense_shares',
                'constraints': [models.UniqueConstraint(fields=('expense', 'user'), name='uq_expense_share')],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group'], name='idx_expenses_group'),
        ),
    ]
