# Generated by Django 5.1.15 on 2026-07-10 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category_label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('amount_paise', models.BigIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('participant_ids', models.JSONField(default=list)),
                ('position', models.IntegerField(default=0)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.expense')),
            ],
            options={
                'db_table': 'expense_items',
                'indexes': [models.Index(fields=['expense', 'position'], name='idx_expense_items')],
            },
        ),
    ]
