# Generated by Django 5.1.15 on 2026-07-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recategorize_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(default='other', max_length=24),
        ),
    ]
