# Generated by Django 5.1.15 on 2026-07-13 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_backfill_group_friendships'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('issue', 'issue'), ('feedback', 'feedback')], default='feedback', max_length=8)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.user')),
            ],
            options={
                'db_table': 'feedback',
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_feedback_user')],
            },
        ),
    ]
